name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
    steps:
      - run: echo "Hoge"
        if: ${{ false }}
      - run: echo "Fuga"
        if: ${{ true }}
